feat: load env variables from single .env and warn when not set
anon-dot-com/examples pull request #29
Opened 2024-08-14 03:26 UTC by rusty-jules

Loads environment variables for each project from a single `.env` file and warns when required environment variables are missing.

Also consolidates the variables names across projects, e.g.

`PLASMO_PUBLIC_ANON_ENVIRONMENT` -> `PLASMO_PUBLIC_ANON_ENV`
`PLASMO_PUBLIC_ANON_CLIENT_ID` -> `PLASMO_PUBLIC_SDKCLIENT_ID`

Note that each project that uses `load_env.js` must now include `dotenv` as a dependency,
since `link_env.js` uses the project that it is run in's `node_modules` folder.

2024-08-14 03:54 UTC, grant requested changes
Good job deleting some unused config between samples. Overall I appreciate deleting some of the env config but I strongly believe we should try to keep our samples isolated from parent folders and keep our npm scripts clean. There are some ways we can do that.

2024-08-14 03:54 UTC, grant commented on connect-react/package.json
> +    "start": "NODE_PATH='./connect-react' ../load_env.js react-scripts start",
This code makes this sample dependent on the parent directory, .., which is not ideal.

2024-08-14 03:54 UTC, grant commented on load_env.js
> +// Utility to load environment variables into the various frontends
All of our users only have 1 frontend, not many.

So this change makes it hard for a user to use a sample in isolation.

Can we think of a different solution?

2024-08-14 03:54 UTC, grant commented on runtime-extension/package.json
> -    "dev": "plasmo dev",
I don't think the new commands are better than these old ones

2024-08-14 05:00 UTC, samgreen approved these changes

2024-08-14 05:00 UTC, samgreen commented on runtime-extension/yarn.lock
> +  version "16.4.5"
Do we have two dependencies named dotenv with different versions?

2024-08-14 18:58 UTC, rusty-jules commented on connect-react/package.json
> +    "start": "NODE_PATH='./connect-react' ../load_env.js react-scripts start",
I'm not sure there is a way to have a single `.env` _and_ not have the sub-folder depend on the parent folder. This is a compromise to turning the example repo into a single example with no sub projects, which will be a big refactor a change to how the examples work fundamentally

2024-08-14 18:58 UTC, rusty-jules commented on connect-react/package.json
> +    "start": "NODE_PATH='./connect-react' ../load_env.js react-scripts start",
Even with a single `ANON_API_KEY` environment variable, you would still need to copy it into every project

2024-08-14 18:59 UTC, rusty-jules commented on load_env.js
> +// Utility to load environment variables into the various frontends
Yes but all of our users use a different frontend (some react, some vue, etc.)

2024-08-14 19:02 UTC, rusty-jules commented on load_env.js
> +// Utility to load environment variables into the various frontends
I can only really think of creating docs for each frontend and explaining that they must edit the console's `.env` file for the framework of their choice - which is explicitly what this PR is trying to resolve (drop-in .env file from console w/o editing)

2024-08-14 19:03 UTC, rusty-jules commented on runtime-extension/package.json
> -    "dev": "plasmo dev",
This is abstracted away from the user via `yarn run dev`. I'm open to other ideas!

2024-08-14 19:06 UTC, rusty-jules commented on load_env.js
> +  dotenv.config({path: "../.env.example"})
Unintuitivly, yes! As the comment notes "first value set wins" so we want `.env` to take precedence over `.env.example`, so any empty values in `.env.example` are set by `.env`, while any default values in `.env.example` like `ANON_CHROME_EXTENSION_ID` don't need to be present in `.env` but can be overridden

2024-08-14 20:02 UTC, grant reviewed
I'd rather have each project have a separate `.env` file.

Having a `load_env.js` file seems unnecessary to run the project.

---

Example multiple `.env` per project: https://github.com/stripe-samples/accept-a-payment

2024-08-14 20:06 UTC, rusty-jules commented
> I'd rather have each project have a separate `.env` file.
> 
> 
> 
> Having a `load_env.js` file seems unnecessary to run the project.
> 
> 
> 
> ---
> 
> 
> 
> Example multiple `.env` per project: https://github.com/stripe-samples/accept-a-payment

Then I'm not sure why we have an issue at all as is this the current set up using symlinks to remove an extra step of copying .envs for users

2024-08-15 00:22 UTC, rusty-jules commented on runtime-extension/yarn.lock
> +  version "16.4.5"
Nice catch - not sure why the old one didn't get deleted when package.json got updated, it could be because another package is depending on it! Will double check

2024-08-15 00:58 UTC, rusty-jules commented
After some discussion, we decided to move `load_env.js` into each individual project, which would have brought many benefits

- self-encapsulate every project so they can be copied out of the examples folder
- remove the need for the heavy `yarn script` commands
- move `load_env.js` to be called from the project's typescript to remove the need for child process
- hardcode the `PREFIX` for each folder's load_env to remove the need for a generic switch case

However, some frameworks (such as react) are unable to use `dotenv` since it relies on OS packages like `fs`, and thus cannot be call `loadEnv` from within their frameworks.

Path forward is to have the `.env` file from the console contain every variant of environment variable so it can be dropped into any of the individual example projects and just work. Once that's the case we can remove the symlink'd .env files as well.

2024-08-15 00:58 UTC, rusty-jules commented
After some discussion, we decided to move `load_env.js` into each individual project, which would have brought many benefits

- self-encapsulate every project so they can be copied out of the examples folder
- remove the need for the heavy `yarn script` commands
- move `load_env.js` to be called from the project's typescript to remove the need for child process
- hardcode the `PREFIX` for each folder's load_env to remove the need for a generic switch case

However, some frameworks (such as react) are unable to use `dotenv` since it relies on OS packages like `fs`, and thus cannot be call `loadEnv` from within their frameworks.

Path forward is to have the `.env` file from the console contain every variant of environment variable so it can be dropped into any of the individual example projects and just work. Once that's the case we can remove the symlink'd .env files as well.

2024-08-15 00:58 UTC, closed without merging